name: NATS Spring Boot Starter CI/CD

on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4
        id: checkout
      # Setup JDK
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
        id: setup_jdk
      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.9
          validate-wrappers: true
        id: setup_gradle
      # Gradle Build
      - name: Gradle build
        run: ./gradlew assemble
        id: gradle_build
      # Gradle publish (only on when tagged)
      - name: Gradle publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "Publishing using version $VERSION. GitHub username is: $GITHUB_ACTOR"
          ./gradlew -Pversion=$VERSION publish
        if: github.ref_type == 'tag'
        id: gradle_publish